language: java
# Enable container-based infrastructure
# see https://docs.travis-ci.com/user/reference/overview/
sudo: false

jdk:
  - oraclejdk8

notifications:
  email: true

install:
- cmake --version
- git submodule init
- git submodule update

script:
- ./mvnw -Pcore-test clean install && cmake . && ctest .
